# Created using wingetcreate 1.9.4.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.9.0.schema.json

PackageIdentifier: Biblivre.org.br.BiblivreInternacional
PackageVersion: 5.0.5
InstallerType: nullsoft
Installers:
- Architecture: x64
  InstallerUrl: https://biblivre.org.br/index.php/baixar/category/5-biblivre-5?download=12:instalador-biblivre-5
  InstallerSha256: 7613BCCE85765AE408E855E052DAD7D11D78F3F33128CABCBD0119BE4711980D
ManifestType: installer
ManifestVersion: 1.9.0
