# Created using wingetcreate 1.9.4.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.9.0.schema.json

PackageIdentifier: Biblivre.org.br.BiblivreInternacional
PackageVersion: 5.0.5
PackageLocale: en-US
Publisher: Biblivre.org.br
PackageName: Biblivre Internacional
License: UNSPECIFIED
Copyright: Biblivre.org.br © GPL
ShortDescription: Sistema de Automação de Bibliotecas
ManifestType: defaultLocale
ManifestVersion: 1.9.0
