# Created using wingetcreate 1.10.3.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.10.0.schema.json

PackageIdentifier: TimKosse.FileZilla
PackageVersion: 3.69.1
PackageLocale: en-US
Publisher: Tim Kosse
PackageName: FileZilla
License: LOCAL
Copyright: Tim Kosse
ShortDescription: FileZilla FTP Client
ManifestType: defaultLocale
ManifestVersion: 1.10.0
